[project]
keywords = ["fountain", "scriptwriting", "script"]
name = "fountain"
version = "0.1.0"
description = "a python fountain script parser"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
authors = [{ name = "Manuel Senfft", email = "info@tagirijus.de" }]
dependencies = []

[project.urls]
repository = "https://github.com/Tagirijus/fountain"

[dependency-groups]
dev = ["pytest>=8.4.2"]

[build-system]
requires = ["uv_build>=0.9.5,<0.10.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-root = ""
